import { ApiProperty } from '@nestjs/swagger';
import { IsDateString, IsUUID, IsString, IsOptional, IsEmail } from 'class-validator';

export class CreateBookingDto {
  @ApiProperty({ example: '83a9c479-e976-49c8-9631-81c1439b20f3', description: 'The quote ID generated by the estimator' })
  @IsUUID()
  quoteId!: string;

  @ApiProperty({ example: '2026-08-24T09:00:00.000Z', description: 'Selected moving date and time' })
  @IsDateString()
  movingDate!: string;

  @ApiProperty({ example: 'Edward', required: false })
  @IsString()
  @IsOptional()
  firstName?: string;

  @ApiProperty({ example: 'Moll', required: false })
  @IsString()
  @IsOptional()
  lastName?: string;

  @ApiProperty({ example: 'edward@example.com', required: false })
  @IsEmail()
  @IsOptional()
  email?: string;

  @ApiProperty({ example: '(602) 555-0199', required: false })
  @IsString()
  @IsOptional()
  phone?: string;

  @ApiProperty({ example: '123 Phoenix Way', required: false })
  @IsString()
  @IsOptional()
  addressLine1?: string;

  @ApiProperty({ example: 'Suite 4', required: false })
  @IsString()
  @IsOptional()
  addressLine2?: string;

  @ApiProperty({ example: 'fcm_token_123', required: false })
  @IsString()
  @IsOptional()
  fcmToken?: string;
}
