import { ApiProperty } from '@nestjs/swagger';
import { IsDateString, IsUUID } from 'class-validator';

export class CreateBookingDto {
  @ApiProperty({ example: '83a9c479-e976-49c8-9631-81c1439b20f3', description: 'The quote ID generated by the estimator' })
  @IsUUID()
  quoteId!: string;

  @ApiProperty({ example: '2026-08-24T09:00:00.000Z', description: 'Selected moving date and time' })
  @IsDateString()
  movingDate!: string;
}
